---    
# Install mongodb
- hosts: all
  become: yes
  become_method: sudo
  roles:
  - role: install-mongod

# Restart Primary taking into account the new configuration (/etc/mongod.conf)
- hosts: primary
  become: yes
  become_method: sudo
  roles:
  - role: restart-mongod

# Initiate the replicaset and create the admin users
- hosts: primary
  become: yes
  become_method: sudo
  roles:
  - role: initiate-replica-set
  - role: wait-master
  - role: create-admin-users

# Create key file
- hosts: localhost
  tasks:
  - name: create key file locally
    local_action: shell openssl rand -base64 755 > /tmp/mongodb-keyfile

# Copy key file to each node
- hosts: all
  become: yes
  become_method: sudo
  roles:
  - role: set-key-files

# Restart Primary taking into account the new configuration (auth / keyFile option defined in /etc/mongod.conf)
- hosts: primary
  become: yes
  become_method: sudo
  roles:
  - role: restart-mongod
  - role: wait-master

# Restart Secondaries taking into account the new configuration (auth / keyFile option defined in /etc/mongod.conf)
- hosts: secondary
  become: yes
  become_method: sudo
  roles:
  - role: restart-mongod
  - role: wait-connection

# Add members to the replicaset and create user for the database
- hosts: primary
  become: yes
  become_method: sudo
  roles:
  - role: add-members
