---

- name: check if mongo already installed
  stat: path=/usr/bin/mongo
  register: mongo_bin

#- name: End the play if the mongo already installed
#  action: fail msg="MongoDB is already installed."
#  when: mongo_bin.stat.exists == True

- name: MongoDB | Fetch 10Gen signing key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
  when: mongo_bin.stat.exists == False

- name: MongoDB | Add 10Gen repository
  shell:
    echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list
    creates=/etc/apt/sources.list.d/mongodb-org-3.2.list
  when: mongo_bin.stat.exists == False

- name: install mongodb
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools
  when: mongo_bin.stat.exists == False

- name: MongoDB - stop server
  service: name=mongod state=stopped
  when: mongo_bin.stat.exists == False

- name: Create the data directory
  file: path={{ mongodb_datadir_prefix }} owner=mongodb state=directory

- name: copy configuration file with authentication parameters
  copy: src=mongod.conf dest=/etc/mongod.conf mode=0644

- name: copy security key file to nodes
  copy: src=/tmp/mongodb-keyfile dest=/etc/mongodb-keyfile mode=0400

- name: change access right of key file
  file: path=/etc/mongodb-keyfile state=file owner=mongodb group=mongodb

- name: MongoDB | Ensure deamon is running correctly
  service: name=mongod state=restarted 

- name: copy initRS script
  template: src=initRS.j2 dest=/tmp/initRS.js
  when: inventory_hostname in groups['primary']

- name: initiate replica set from first primary
  shell: mongo < /tmp/initRS.js
  when: inventory_hostname in groups['primary']

- name: copy master script
  template: src=master.j2 dest=/tmp/master.js
  when: inventory_hostname in groups['primary']

- name: wait for host to become primary
  shell: mongo < /tmp/master.js
  when: inventory_hostname in groups['primary']

- debug: msg="current host expected value:{{ groups['primary'][0] }} - current host current value:{{ inventory_hostname }}"
  when: inventory_hostname in groups['primary']

- name: copy createAdmin script
  template: src=createAdmins.j2 dest=/tmp/createAdmins.js
  when: inventory_hostname in groups['primary']

- name: create administrator users
  shell: mongo < /tmp/createAdmins.js
  when: inventory_hostname in groups['primary']

- name: copy addMembers script
  template: src=addMembers.j2 dest=/tmp/addMembers.js
  when: inventory_hostname in groups['primary']

- name: add members to the replica set
  shell: mongo < /tmp/addMembers.js
  when: inventory_hostname in groups['primary']

- name: copy configuration file with authentication parameters
  copy: src=mongod2.conf dest=/etc/mongod.conf mode=0644

- name: MongoDB | Ensure deamon is running correctly
  service: name=mongod state=restarted