





# Environment Variables
# For aws shared-services account
export AWS_ACCESS_KEY_ID=AKIAI7B7X2MXL73TXRGA
export AWS_SECRET_ACCESS_KEY=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
export AWS_DEFAULT_REGION=us-east-1